/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dag.gui;

import com.mxgraph.layout.hierarchical.mxHierarchicalLayout;
import com.mxgraph.layout.mxCircleLayout;
import com.mxgraph.layout.mxCompactTreeLayout;
import com.mxgraph.layout.mxEdgeLabelLayout;
import com.mxgraph.layout.mxFastOrganicLayout;
import com.mxgraph.layout.mxIGraphLayout;
import com.mxgraph.layout.mxParallelEdgeLayout;
import com.mxgraph.layout.mxPartitionLayout;
import com.mxgraph.layout.mxStackLayout;
import com.mxgraph.swing.mxGraphComponent;
import dag.model.RelationshipEdge;
import dag.model.TableVertex;
import java.awt.BorderLayout;
import org.jgrapht.ext.JGraphXAdapter;
import org.jgrapht.graph.DirectedAcyclicGraph;

/**
 *
 * @author Evandro
 */
public class DAGVisualization extends javax.swing.JDialog {
    //private DirectedAcyclicGraph<TableVertex, RelationshipEdge> graph;
    
    public void loadGraph(DirectedAcyclicGraph<TableVertex, RelationshipEdge> graph, int graphLayoutOption){
        // Adapter to convert JGraphT to JGraphX.
        JGraphXAdapter<TableVertex, RelationshipEdge> adapter = new JGraphXAdapter(graph);        
     
        Object parentJGraphX = adapter.getDefaultParent();
        
        //mxIGraphLayout layout = new mxHierarchicalLayout(adapter);        
        mxIGraphLayout layout = getGraphLayout(graphLayoutOption, adapter); 
        
        layout.execute(parentJGraphX);        
        
        adapter.getView().setScale(1.5);                
        
        mxGraphComponent graphComponent = new mxGraphComponent(adapter);        
        
        getContentPane().add(graphComponent, BorderLayout.CENTER);
    }
    
    private mxIGraphLayout getGraphLayout(int graphLayoutOption, JGraphXAdapter<TableVertex, RelationshipEdge> adapter){
        
        switch (graphLayoutOption){
            case 0:
                mxHierarchicalLayout layout = new mxHierarchicalLayout(adapter);                
                return layout;
            case 1:
                return new mxCircleLayout(adapter);
            case 2:
                return new mxCompactTreeLayout(adapter);
            case 3:
                return new mxEdgeLabelLayout(adapter);
            case 4:
                return new mxFastOrganicLayout(adapter);
            case 5:
                return new mxParallelEdgeLayout(adapter);
            case 6:
                return new mxPartitionLayout(adapter);
            case 7:
                return new mxStackLayout(adapter);
        }   
        
        return new mxHierarchicalLayout(adapter);
    }
    
    /**
     * Creates new form GraphVisualizationJDialog
     */
    public DAGVisualization(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //initComponents();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAGVisualization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAGVisualization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAGVisualization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAGVisualization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DAGVisualization dialog = new DAGVisualization(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
