/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dag.gui;

import dag.model.RelationshipEdge;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jdbc_connection.GenericConnection;

/**
 *
 * @author Evandro
 */
public class EdgeCreatorJDialog extends javax.swing.JDialog {
    private RelationshipEdge edge;
    private boolean cancel;
    
    private GenericConnection rdbConnection;
    private DatabaseMetaData rdb_metadata;
    
    /**
     * Creates new form EdgeCreatorJDialog
     */
    public EdgeCreatorJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public boolean isCancel() {
        return cancel;
    }
    
    public RelationshipEdge getEdge() {
        return edge;
    }

    public void setEdge(RelationshipEdge edge) {
        this.edge = edge;
        
        writeControls();
    }

    public void setRdbConnection(GenericConnection rdbConnection) {
        this.rdbConnection = rdbConnection;
    }
    
    public void writeControls(){
        txtSourceVertex.setText(this.edge.getSource().getTableName());
        txtTargetVertex.setText(this.edge.getTarget().getTableName());
        
        if (this.edge.getSource().getTableName().equalsIgnoreCase(edge.getOneSideEntity())){ 
            this.optSourceOne.setSelected(true);
            this.optTargetMany.setSelected(true);
        } else {
            this.optTargetOne.setSelected(true);
            this.optSourceMany.setSelected(true);
        }        
        
        loadSourceFields();
        loadTargetFields();
        
        cmbSourceKey.setSelectedItem(this.edge.getKeySource());
        cmbTargetKey.setSelectedItem(this.edge.getKeyTarget());
    }
    
    public void readControls(){
        if (optSourceOne.isSelected()){
            this.edge.setOneSideEntity(txtSourceVertex.getText());
            this.edge.setPkOneSide(cmbSourceKey.getSelectedItem().toString());
            this.edge.setManySideEntity(txtTargetVertex.getText());
            this.edge.setFkManySide(cmbTargetKey.getSelectedItem().toString());
        } else {
            this.edge.setOneSideEntity(txtTargetVertex.getText());
            this.edge.setPkOneSide(cmbTargetKey.getSelectedItem().toString());
            this.edge.setManySideEntity(txtSourceVertex.getText());
            this.edge.setFkManySide(cmbSourceKey.getSelectedItem().toString());
        }
    }
    
    public void loadSourceFields(){        
        cmbSourceKey.removeAllItems();
        
        ResultSet rs;
        try {
            rdb_metadata = rdbConnection.getConnection().getMetaData();
            rs = rdb_metadata.getColumns("", "", txtSourceVertex.getText(), "");
            while (rs.next()) {
                cmbSourceKey.addItem(rs.getString("COLUMN_NAME"));
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public void loadTargetFields(){
        cmbTargetKey.removeAllItems();
        
        ResultSet rs;
        try {
            rdb_metadata = rdbConnection.getConnection().getMetaData();
            rs = rdb_metadata.getColumns("", "", txtTargetVertex.getText(), "");
            while (rs.next()) {
                cmbTargetKey.addItem(rs.getString("COLUMN_NAME"));
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSource = new javax.swing.ButtonGroup();
        buttonGroupTarget = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtSourceVertex = new javax.swing.JTextField();
        cmbSourceKey = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        optSourceOne = new javax.swing.JRadioButton();
        optSourceMany = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTargetVertex = new javax.swing.JTextField();
        cmbTargetKey = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        optTargetOne = new javax.swing.JRadioButton();
        optTargetMany = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edge Creator");

        jLabel1.setText("Source Vertex:");

        txtSourceVertex.setEditable(false);

        cmbSourceKey.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Source Key:");

        buttonGroupSource.add(optSourceOne);
        optSourceOne.setText("one");
        optSourceOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSourceOneActionPerformed(evt);
            }
        });

        buttonGroupSource.add(optSourceMany);
        optSourceMany.setText("many");
        optSourceMany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSourceManyActionPerformed(evt);
            }
        });

        jLabel3.setText("Source Side:");

        jLabel4.setText("Target Vertex:");

        txtTargetVertex.setEditable(false);

        cmbTargetKey.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Target Key:");

        buttonGroupTarget.add(optTargetOne);
        optTargetOne.setText("one");
        optTargetOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTargetOneActionPerformed(evt);
            }
        });

        buttonGroupTarget.add(optTargetMany);
        optTargetMany.setText("many");
        optTargetMany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optTargetManyActionPerformed(evt);
            }
        });

        jLabel6.setText("Target Side:");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSourceVertex)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optSourceOne)
                        .addGap(18, 18, 18)
                        .addComponent(optSourceMany))
                    .addComponent(cmbSourceKey, 0, 145, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTargetVertex)
                            .addComponent(cmbTargetKey, 0, 145, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optTargetOne)
                                .addGap(18, 18, 18)
                                .addComponent(optTargetMany)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTargetVertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTargetKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(optTargetOne)
                            .addComponent(optTargetMany)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtSourceVertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSourceKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(optSourceOne)
                            .addComponent(optSourceMany)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optSourceOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSourceOneActionPerformed
        optTargetMany.setSelected(true);
    }//GEN-LAST:event_optSourceOneActionPerformed

    private void optSourceManyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSourceManyActionPerformed
        optTargetOne.setSelected(true);
    }//GEN-LAST:event_optSourceManyActionPerformed

    private void optTargetOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTargetOneActionPerformed
        optSourceMany.setSelected(true);
    }//GEN-LAST:event_optTargetOneActionPerformed

    private void optTargetManyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optTargetManyActionPerformed
        optSourceOne.setSelected(true);
    }//GEN-LAST:event_optTargetManyActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cancel = true;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.cancel =  false;
        readControls();
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EdgeCreatorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EdgeCreatorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EdgeCreatorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EdgeCreatorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EdgeCreatorJDialog dialog = new EdgeCreatorJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroupSource;
    private javax.swing.ButtonGroup buttonGroupTarget;
    private javax.swing.JComboBox<String> cmbSourceKey;
    private javax.swing.JComboBox<String> cmbTargetKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton optSourceMany;
    private javax.swing.JRadioButton optSourceOne;
    private javax.swing.JRadioButton optTargetMany;
    private javax.swing.JRadioButton optTargetOne;
    private javax.swing.JTextField txtSourceVertex;
    private javax.swing.JTextField txtTargetVertex;
    // End of variables declaration//GEN-END:variables
}
